### ISSUE TITLE
v0.6.5-alpha.18版本 /v1/embeddings 报错

### ISSUE THREAD

**Issue by yorke669** [songquanpeng/one-api#1316]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x]  我已确认目前没有类似 issue
+ [x]  我已确认我已升级到最新版本
+ [x]  我已完整查看过项目 README，尤其是常见问题部分
+ [x]  我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用版本： ghcr.io/songquanpeng/one-api:v0.6.5-alpha.18

向量化知识失败

fastgpt_oneapi  | [ERR] 2024/04/12 - 17:45:41 | 2024041217454176454496988398752 | request: POST /v1/embeddings
fastgpt_oneapi  | [ERR] 2024/04/12 - 17:45:41 | 2024041217454176454496988398752 | request body: {
fastgpt_oneapi  |   "model": "embedding-2",
fastgpt_oneapi  |   "input": [
fastgpt_oneapi  |     "qweqwe\neeee"
fastgpt_oneapi  |   ]
fastgpt_oneapi  | }
fastgpt_oneapi  | [GIN] 2024/04/12 - 17:45:41 | 2024041217454176454496988398752 | 500 |    1.271732ms |      172.24.0.6 |    POST /v1/embeddings
fastgpt         | Embedding Error eK [Error]: 500 Panic detected, error: interface conversion: interface {} is []interface {}, not string. Please submit an issue with the related log here: https://github.com/songquanpeng/one-api
fastgpt         |     at eL.generate (/app/projects/app/.next/server/chunks/80555.js:21:70210)
fastgpt         |     at af.makeStatusError (/app/projects/app/.next/server/chunks/80555.js:21:81687)
fastgpt         |     at af.makeRequest (/app/projects/app/.next/server/chunks/80555.js:21:82610)
fastgpt         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fastgpt         |     at async c (/app/projects/app/.next/server/chunks/50444.js:30:1260)
fastgpt         |     at async w (/app/projects/app/.next/server/chunks/50444.js:22:399)
fastgpt         |     at async Promise.all (index 0)
fastgpt         |     at async u (/app/projects/app/.next/server/chunks/16378.js:54:26810)
fastgpt         |     at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:3043 {
fastgpt         |   status: 500,
fastgpt         |   headers: {
fastgpt         |     'content-length': '225',
fastgpt         |     'content-type': 'application/json; charset=utf-8',
fastgpt         |     date: 'Fri, 12 Apr 2024 09:45:41 GMT',
fastgpt         |     'x-oneapi-request-id': '2024041217454176454496988398752'
fastgpt         |   },
fastgpt         |   error: {
fastgpt         |     message: 'Panic detected, error: interface conversion: interface {} is []interface {}, not string. Please submit an issue with the related log here: https://github.com/songquanpeng/one-api',
fastgpt         |     type: 'one_api_panic'
fastgpt         |   },
fastgpt         |   code: undefined,
fastgpt         |   param: undefined,
fastgpt         |   type: 'one_api_panic'
fastgpt         | }

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by ldm4305** [comment]
修改relay/adaptor/zhipu/adaptor.go文件，将
Input: request.Input.(string)
改为
Input: strings.Join(request.ParseInput(), " ")
，重新编译。
