### ISSUE TITLE
AWS  Bedrock 的  Claude 模型报错（v0.6.6-alpha.11 版本）

### ISSUE THREAD

**Issue by Caixiaopig** [songquanpeng/one-api#1384]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在 **v0.6.6-alpha.11** 版本中，AWS  Bedrock 的  Claude 模型报错，错误提示如下：

**API返回:**
```
API Error: Status Code 500, {"error":{"message":"Panic detected, error: runtime error: invalid memory address or nil pointer dereference. Please submit an issue with the related log here: https://github.com/songquanpeng/one-api","type":"one_api_panic"}}
```

**终端日志：**
```
one-api  | [GIN] 2024/04/27 - 23:46:28 | 2024042723462868196056351855327 | 500 |    2.615974ms |    58.32.17.218 |    POST /v1/chat/completions
one-api  | [ERR] 2024/04/27 - 23:46:28 | 2024042723462868196056351855327 | stacktrace from panic: goroutine 40 [running]:
one-api  | runtime/debug.Stack()
one-api  | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
one-api  | github.com/songquanpeng/one-api/router.SetRelayRouter.RelayPanicRecover.func2.1()
one-api  | 	/build/middleware/recover.go:18 +0xc5
one-api  | panic({0x100be80?, 0x3ca0070?})
one-api  | 	/usr/local/go/src/runtime/panic.go:770 +0x132
one-api  | github.com/songquanpeng/one-api/relay/controller.RelayErrorHandler(0x0)
one-api  | 	/build/relay/controller/error.go:62 +0x25
one-api  | github.com/songquanpeng/one-api/relay/controller.RelayTextHelper(0xc000598900)
one-api  | 	/build/relay/controller/text.go:91 +0xe79
one-api  | github.com/songquanpeng/one-api/controller.relayHelper(0xc000001715?, 0x1155b58?)
one-api  | 	/build/controller/relay.go:37 +0x52
one-api  | github.com/songquanpeng/one-api/controller.Relay(0xc000598900)
one-api  | 	/build/controller/relay.go:50 +0x145
one-api  | github.com/gin-gonic/gin.(*Context).Next(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api  | github.com/songquanpeng/one-api/router.SetRelayRouter.Distribute.func4(0xc000598900)
one-api  | 	/build/middleware/distributor.go:56 +0x1a5
one-api  | github.com/gin-gonic/gin.(*Context).Next(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api  | github.com/songquanpeng/one-api/router.SetRelayRouter.TokenAuth.func3(0xc000598900)
one-api  | 	/build/middleware/auth.go:143 +0x492
one-api  | github.com/gin-gonic/gin.(*Context).Next(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api  | github.com/songquanpeng/one-api/router.SetRelayRouter.RelayPanicRecover.func2(0xc000598998?)
one-api  | 	/build/middleware/recover.go:31 +0x45
one-api  | github.com/gin-gonic/gin.(*Context).Next(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api  | main.main.Sessions.func3(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-contrib/sessions@v1.0.0/sessions.go:54 +0x169
one-api  | github.com/gin-gonic/gin.(*Context).Next(...)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
one-api  | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xdd
one-api  | github.com/gin-gonic/gin.(*Context).Next(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api  | main.main.RequestId.func2(0xc000598900)
one-api  | 	/build/middleware/request-id.go:16 +0x106
one-api  | github.com/gin-gonic/gin.(*Context).Next(...)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
one-api  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x7a
one-api  | github.com/gin-gonic/gin.(*Context).Next(...)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
one-api  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00007c1a0, 0xc000598900)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66e
one-api  | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00007c1a0, {0x35c0cb8, 0xc00086a540}, 0xc0003597a0)
one-api  | 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1b2
one-api  | net/http.serverHandler.ServeHTTP({0x35bd4e0?}, {0x35c0cb8?, 0xc00086a540?}, 0x6?)
one-api  | 	/usr/local/go/src/net/http/server.go:3137 +0x8e
one-api  | net/http.(*conn).serve(0xc0004aaf30, {0x35c30c8, 0xc0000c2a50})
one-api  | 	/usr/local/go/src/net/http/server.go:2039 +0x5e8
one-api  | created by net/http.(*Server).Serve in goroutine 1
one-api  | 	/usr/local/go/src/net/http/server.go:3285 +0x4b4
one-api  |
one-api  | [ERR] 2024/04/27 - 23:46:28 | 2024042723462868196056351855327 | request: POST /v1/chat/completions
one-api  | [ERR] 2024/04/27 - 23:46:28 | 2024042723462868196056351855327 | request body: {"messages":[{"role":"system","content":"Current model: claude-3-opus-20240229\n\nYou are a helpful assistant. You can help me by answering my questions. You can also ask me questions."},{"role":"user","content":"生命的意义是什么？"}],"model":"claude-3-opus-20240229","temperature":0.5,"top_p":1,"stream":true}
```

**复现步骤**
调用API接口

**预期结果**
正常对话

**相关截图**
如果没有的话，请删除此节。

**Comment by songquanpeng** [comment]
目前缺key调试

**Comment by Godzillas** [comment]
服务正常，请求报错：
API Error: Status Code 401, {"type":"error","error":{"type":"authentication_error","message":"x-api-key header is required"}}

可提供key 调试

**Comment by Caixiaopig** [comment]
退回到 **v0.6.6-alpha.9** 就正常了，不知道这中间修改了什么？

**Comment by songquanpeng** [comment]
> ？

因为进行了一个小规模重构，重构完我想测试发现别人之前给的key给我撤销了

**Comment by Caixiaopig** [comment]
我给你新的 key

**Comment by songquanpeng** [comment]
panic 的问题解决了，v0.6.6-alpha.13 试一下呢，我现在还是没有 key 没法测试
