### ISSUE TITLE
并发造成的闪退

### ISSUE THREAD

**Issue by zsinba** [songquanpeng/one-api#1476]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
并发上来后， 远端访问变慢； 
one-api 会出现闪退现象。 

**复现步骤**
随着请求并发数越来越多， 远端接口越来越慢，以及达到若干秒才返回 。 
此时客户端请求未停止， 各界的请求越来越多，造成 one-api 闪退

**预期结果**
正常运行，不闪退
**相关截图**
`[ERR] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | relay error (channel #44):  
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 10) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 9) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 8) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 7) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 6) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 5) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 4) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 3) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 2) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277961529691709632 | using channel #44 to retry (remain times 1) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 6) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 5) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 4) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 3) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 2) 
[INFO] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | using channel #44 to retry (remain times 1) 
[GIN] 2024/05/28 - 15:08:52 | 2024052815085277975491880923474 | 502 |    4.234219ms |     172.17.0.56 |    POST /v1/embeddings
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46e436]

goroutine 148169 [running]:
fmt.(*buffer).writeString(...)
        /usr/local/go/src/fmt/print.go:108
fmt.(*fmt).padString(0x0?, {0x0, 0x2e})
        /usr/local/go/src/fmt/format.go:110 +0x24a
fmt.(*fmt).fmtS(0xc003da9cf0?, {0x0?, 0xc009eba040?})
        /usr/local/go/src/fmt/format.go:359 +0x39
fmt.(*pp).fmtString(0xc0070697a0?, {0x0?, 0x44545c?}, 0x4e88680?)
        /usr/local/go/src/fmt/print.go:497 +0xc5
fmt.(*pp).printArg(0xc009eba000, {0xf89420?, 0xc00a0aa150}, 0x73)
        /usr/local/go/src/fmt/print.go:741 +0x1bb
fmt.(*pp).doPrintf(0xc009eba000, {0x113d5b0, 0x1d}, {0xc003da9f70?, 0x2, 0x2})
        /usr/local/go/src/fmt/print.go:1077 +0x39e
fmt.Sprintf({0x113d5b0, 0x1d}, {0xc003da9f70, 0x2, 0x2})
        /usr/local/go/src/fmt/print.go:239 +0x53
github.com/songquanpeng/one-api/common/logger.Errorf({0x2189188, 0xc00a1b0540}, {0x113d5b0?, 0xc007e56bc0?}, {0xc003da9f70?, 0xc009e8e140?, 0x20?})
        /build/common/logger/logger.go:82 +0x36
github.com/songquanpeng/one-api/controller.processChannelRelayError({0x2189188, 0xc00a1b0540}, 0xc003da9fd0?, {0xc002ff0a38, 0x15}, 0xc002ffe5a0)
        /build/controller/relay.go:119 +0xac
created by github.com/songquanpeng/one-api/controller.Relay in goroutine 146188
        /build/controller/relay.go:59 +0x2f9

`

**Comment by 0x5c0f** [comment]
一般说并发故障的，都是用sqlite库的。

**Comment by zsinba** [comment]
这是单机版本的 One-api； 
独立机器的 Mysql 和 Redis；

**Comment by 0x5c0f** [comment]
> 这是单机版本的 One-api； 独立机器的 Mysql 和 Redis；

服务器负载正常的话，你只能考虑集群了，没有对程序压测过，所以具体能承受多少不是很清楚，另外这个与环境也有一定的关系，go 程序承受理应不会很低，而且你特大量理应也该考虑集群
