### ISSUE TITLE
生成的令牌无法使用

### ISSUE THREAD

**Issue by Ikaros-521** [songquanpeng/one-api#164]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
正常创建渠道后，生成令牌，测试就无法使用。不知道是不是我用错了0.0

**复现步骤**
正常创建渠道后，生成令牌，测试

**预期结果**
能够正常使用

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/40910637/000c5999-5850-45cd-93b7-d019db6b95e6)

![image](https://github.com/songquanpeng/one-api/assets/40910637/1bd8cfdc-21d5-4060-ad1b-3d5ec4964c65)
![image](https://github.com/songquanpeng/one-api/assets/40910637/1ee6d83a-5b86-4f31-83bd-cae74a06937c)
![image](https://github.com/songquanpeng/one-api/assets/40910637/151ff72e-52df-4029-a37a-2969aefa477f)

![image](https://github.com/songquanpeng/one-api/assets/40910637/390505f0-f408-4017-abf9-225032a04d06)

**Comment by Ikaros-521** [comment]
> 这里的测试有报错吗？ ![image](https://user-images.githubusercontent.com/39998050/245830052-9f7df821-e78c-4ba8-97c9-6fb4f0ac4134.png)

没有报错
![image](https://github.com/songquanpeng/one-api/assets/40910637/7a4a7724-ce1a-4d07-ba55-768ebe45e021)

**Comment by songquanpeng** [comment]
我没用过 OpenAI 的 Python，不过这个官方库允许自定义 Base URL 吗？
![image](https://github.com/songquanpeng/one-api/assets/39998050/5ac62657-83c4-4768-af1a-3e680a19b35f)

**Comment by Ikaros-521** [comment]
![image](https://github.com/songquanpeng/one-api/assets/40910637/5be5ee68-67d5-4721-9b53-1001c069a14c)
搭的next 设了密钥也是没法使用

**Comment by songquanpeng** [comment]
官方的 Python 库的自定义我不清楚可不可以自定义 Base URL。

至于 Next 那个，这个非常奇怪，invalid_api_key 是 OpenAI 的服务器返回的，说明 key 有问题，但是你的截图里又显示测试成功。

你在群里问一下有没有类似情况的吧。

**Comment by Ikaros-521** [comment]
> 官方 Python 库好像不能改 base_url，那个变量貌似是给 Azure 的，不过我不确定。
> 
> 应该在支持修改 Base URL 的工具里使用。

修改base我测过 https://openai-pag.wangzhishi.net/v1  没什么问题。
不过现在测的没改base，直接调官方接口也不行

**Comment by songquanpeng** [comment]
那就有可能是网络问题了。

**Comment by Ikaros-521** [comment]
> 那就有可能是网络问题了。

同一网络环境，前后2次测试。
生成的令牌 / 官方API KEY

![image](https://github.com/songquanpeng/one-api/assets/40910637/654569a1-86bf-432a-9ac2-17001f9b5c9e)

**Comment by ChangeYu0229** [comment]
我也遇到了一样的问题 生成的令牌用一键查询工具：https://openai.candy666.top/
提示api不存在

**Comment by songquanpeng** [comment]
> 我也遇到了一样的问题 生成的令牌用一键查询工具：https://openai.candy666.top/ 提示api不存在

这个肯定不行啊，他上面只支持官方 Key。

**Comment by halfu** [comment]
> 我也遇到了一样的问题 生成的令牌用一键查询工具：https://openai.candy666.top/ 提示api不存在

这个系统生成的token需要由one api鉴权，不能直接传递给openai。你需要确定base url是否正确配置为你的one api地址。

**Comment by Ikaros-521** [comment]
> > 我也遇到了一样的问题 生成的令牌用一键查询工具：https://openai.candy666.top/ 提示api不存在
> 
> 这个系统生成的token需要由one api鉴权，不能直接传递给openai。你需要确定base url是否正确配置为你的one api地址。

悟了，不过直接请求 服务器地址（nginx转发了，certbot还没搞）还是报了个错，大佬有遇到吗
```
Traceback (most recent call last):
  File "D:\Miniconda\envs\aivtb\lib\site-packages\openai\api_requestor.py", line 753, in _interpret_response_line
openai.error.APIError: HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="Web site created using create-react-app"/><title>One API</title><script defer="defer" src="/static/js/main.37add8cf.js"></script><link href="/static/css/main.44582e8c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)
```

**Comment by Ikaros-521** [comment]
> > > 我也遇到了一样的问题 生成的令牌用一键查询工具：https://openai.candy666.top/ 提示api不存在
> > 
> > 
> > 这个系统生成的token需要由one api鉴权，不能直接传递给openai。你需要确定base url是否正确配置为你的one api地址。
> 
> 悟了，不过直接请求 服务器地址（nginx转发了，certbot还没搞）还是报了个错，大佬有遇到吗
> 
> ```
> Traceback (most recent call last):
>   File "D:\Miniconda\envs\aivtb\lib\site-packages\openai\api_requestor.py", line 753, in _interpret_response_line
> openai.error.APIError: HTTP code 200 from API (<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#ffffff"/><meta name="description" content="Web site created using create-react-app"/><title>One API</title><script defer="defer" src="/static/js/main.37add8cf.js"></script><link href="/static/css/main.44582e8c.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>)
> ```

结案了，请求加上 /v1后还是不行，换了个官方demo可以了。。。
官方demo有坑啊。。。

**Comment by Ikaros-521** [comment]
> 可以贴一下代码吗？

```
import os
import openai

openai.api_key = "马赛克"
openai.api_base = "马赛克"

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)

```

**Comment by songquanpeng** [comment]
关了哈，如果还有问题，欢迎重开

**Comment by Ikaros-521** [comment]
> 关了哈，如果还有问题，欢迎重开

大佬，群申请一天了，还没审核，哭死
![F9DW1UCS PG`XW0 %%12$HV](https://github.com/songquanpeng/one-api/assets/40910637/23ecf7c6-3156-4f15-909e-da5a9ab69059)

**Comment by songquanpeng** [comment]
az，没看到，是自动审核的，为了防止有机器人设置了等级限制。

**Comment by Ikaros-521** [comment]
> az，没看到，是自动审核的，为了防止有机器人设置了等级限制。

不会吧，我皇冠+呀。。。

**Comment by songquanpeng** [comment]
是这个吗
![image](https://github.com/songquanpeng/one-api/assets/39998050/b1a63532-208e-40ed-808d-55182be93d1e)

**Comment by Ikaros-521** [comment]
> 是这个吗 ![image](https://user-images.githubusercontent.com/39998050/246128667-b1a63532-208e-40ed-808d-55182be93d1e.png)

不是，Ikaros

**Comment by songquanpeng** [comment]
看的你进去了，所以应该是没有发出去。

**Comment by Ikaros-521** [comment]
> QQ 真垃，之前有人说过那个链接无法正常跳转。

www 典 进来了
![6_}(MU~D9BV4F9S~ WU`9PM](https://github.com/songquanpeng/one-api/assets/40910637/345dade1-3cd4-458a-b865-f546b2e70c6e)

**Comment by Ikaros-521** [comment]
![image](https://github.com/songquanpeng/one-api/assets/40910637/9c931342-ac84-4818-9c93-4419018cb4e2)
好几个官方demo都跑不了诶 啊这

**Comment by songquanpeng** [comment]
所以是哪几个跑不了？如果是用到了未实现的 API 确实可能出错。

但是我看最后的那个报错，报错信息应该是“无效的 token”，这个是你传入的 One API 令牌有问题。

**Comment by Ikaros-521** [comment]
> 所以是哪几个跑不了？如果是用到了未实现的 API 确实可能出错。
> 
> 但是我看最后的那个报错，报错信息应该是“无效的 token”，这个是你传入的 One API 令牌有问题。

同一个令牌 在跑model list的时候没问题，别的测了几个都不行。
最关键的 https://api.openai.com/v1/completions，跑不起来

**Comment by songquanpeng** [comment]
这个 API 是支持的。

我新开 issue 来解决该问题。

**Comment by Ikaros-521** [comment]
> 这个 API 是支持的。
> 
> 我新开 issue 来解决该问题。

可以

**Comment by CodeGetters** [comment]
![image](https://github.com/songquanpeng/one-api/assets/109447998/12ec2cf3-dd94-46e3-8a78-9770964c06ed)
请问大佬出现这个问题是啥意思呀，是我配置有问题吗

**Comment by fakeboydxy** [comment]
> ![image](https://private-user-images.githubusercontent.com/109447998/333774127-12ec2cf3-dd94-46e3-8a78-9770964c06ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk3NDIsIm5iZiI6MTcxODA4OTQ0MiwicGF0aCI6Ii8xMDk0NDc5OTgvMzMzNzc0MTI3LTEyZWMyY2YzLWRkOTQtNDZlMy04YTc4LTk3NzA5NjRjMDZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzA0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTRiMmU0NzUwYThkMmYyYzY1M2U2OGEyZTgzYjljY2E4OTZjZjFjOTllMWJmODU3ODdiZTI4OGIyYjE4Zjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bBcfcVXiiglY7EGdOfIumx3041MbDF660FnvssYaQoI) 请问大佬出现这个问题是啥意思呀，是我配置有问题吗
解决了吗
