### ISSUE TITLE
Embedding Error aa [Error]: 503 当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道

### ISSUE THREAD

**Issue by useradd-test** [songquanpeng/one-api#1738]
Embedding Error aa [Error]: 503 当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道 (request id: 2024081408593262123300533081679)
2024-08-14 16:59:32     at t0.generate (/app/projects/app/.next/server/chunks/76420.js:19:87386)
2024-08-14 16:59:32     at rr.makeStatusError (/app/projects/app/.next/server/chunks/76420.js:19:78988)
2024-08-14 16:59:32     at rr.makeRequest (/app/projects/app/.next/server/chunks/76420.js:19:79911)
2024-08-14 16:59:32     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-14 16:59:32     at async i (/app/projects/app/.next/server/chunks/96960.js:177:1589)
2024-08-14 16:59:32     at async T (/app/projects/app/.next/server/chunks/96960.js:169:4414)
2024-08-14 16:59:32     at async Promise.all (index 0)
2024-08-14 16:59:32     at async c (/app/projects/app/.next/server/chunks/96960.js:348:28022)
2024-08-14 16:59:32     at async /app/projects/app/.next/server/chunks/96960.js:350:3241
2024-08-14 16:59:32     at async o (/app/projects/app/.next/server/chunks/96960.js:143:12510) {
2024-08-14 16:59:32   status: 503,
2024-08-14 16:59:32   headers: {
2024-08-14 16:59:32     'content-length': '168',
2024-08-14 16:59:32     'content-type': 'application/json; charset=utf-8',
2024-08-14 16:59:32     date: 'Wed, 14 Aug 2024 08:59:32 GMT',
2024-08-14 16:59:32     'x-oneapi-request-id': '2024081408593262123300533081679'
2024-08-14 16:59:32   },
2024-08-14 16:59:32   request_id: undefined,
2024-08-14 16:59:32   error: {
2024-08-14 16:59:32     message: '当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道 (request id: 2024081408593262123300533081679)',
2024-08-14 16:59:32     type: 'one_api_error'
2024-08-14 16:59:32   },
2024-08-14 16:59:32   code: undefined,
2024-08-14 16:59:32   param: undefined,
2024-08-14 16:59:32   type: 'one_api_error'
2024-08-14 16:59:32 }

**Comment by 125793014** [comment]
我今天也遇到这个问题了，我的是one-api:v0.6.6.1-arm镜像版本。

**Comment by nanbingxyz** [comment]
0.6.10 也遇到了类似的问题，提示“503 当前分组 default 下对于模型 gpt-4o-mini 无可用渠道”。时不时会出现并持续一段时间
