### ISSUE TITLE
多服务器部署，多次刷新后，补全倍率和模型倍率的值不一致

### ISSUE THREAD

**Issue by zzy5066** [songquanpeng/one-api#1856]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在多服务器部署(env正常设置)的情况下，添加了多行的补全倍率和模型倍率，在数据库的options表，也正常更新了数据，看起来一切正常，并且也确认数据库，连接的是同一个。
但是，当我刷新设置==>运营设置后，偶尔会出现默认的补全倍率和模型倍率，意味着没有走数据库，是什么原因？

**复现步骤**
多服务器部署(env正常设置)的情况下，添加了多行的补全倍率和模型倍率，刷新运营设置页面，出现了默认的补全倍率和模型倍率

**预期结果**
要都从数据库获取，无论怎么刷新，应该都要保持最新的和数据库同步的结果
**相关截图**
正常设置后的补全倍率和模型倍率:
![773d6400620d182775721ec507b2d138](https://github.com/user-attachments/assets/bf10a349-4e28-4740-aef6-c6dafee11ccc)
当刷新后，很大概率，出现了默认的补全倍率和模型倍率：
![0064273bd6d8542c65903317090601ea](https://github.com/user-attachments/assets/33dc8826-ba45-437e-be1d-3a600d784e80)

如果没有的话，请删除此节。

**Comment by jacky080808** [comment]
2025-03-04 10:52:29.850 ERROR 1 --- [81.106:3000/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.103 :  | OpenAI sse connection exception data: 

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ai.chat2db.server.web.api.controller.ai.openai.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:61)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jacky080808** [comment]
2025-03-04 10:52:29.850 ERROR 1 --- [81.106:3000/...] .s.w.a.c.a.o.l.OpenAIEventSourceListener.103 :  | OpenAI sse connection exception data: 

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ai.chat2db.server.web.api.controller.ai.openai.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:61)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
这是什么错误啊？
