### ISSUE TITLE
Docker run failed with runtime/cgo: pthread_create failed: Operation not permitted

### ISSUE THREAD

**Issue by songkq** [songquanpeng/one-api#966]
@songquanpeng Hi, could you please give some advice for this issue?

**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

Env:
CentOS-7
![image](https://github.com/songquanpeng/one-api/assets/30183023/ac69c861-9ebc-4ea5-b740-aad0dcf63d72)

```

runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0xdabcab m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0xdabcab
stack: frame={sp:0x7ffe7781a1f0, fp:0x0} stack=[0x7ffe7701b670,0x7ffe7781a680)
0x00007ffe7781a0f0:  0x0000000000069c3f  0x00007ffe7781a118 
0x00007ffe7781a100:  0x0000000000e229f0  0x000000001c000004 
0x00007ffe7781a110:  0x0000000000d98f20  0x0000000000000000 
0x00007ffe7781a120:  0x00007facbee6fc40  0x68007ffe7781a310 
0x00007ffe7781a130:  0x000000c000044000  0x000000c00014e000 
0x00007ffe7781a140:  0x0000000000000000  0x0000000000000000 
0x00007ffe7781a150:  0x0000000000000000  0x0000000000000000 
0x00007ffe7781a160:  0x0000000000000001  0x000000c000044000 
0x00007ffe7781a170:  0x00007ffe7781a358  0x0000000000ddb33d 
0x00007ffe7781a180:  0x00007fac782cd6c0  0x00007ffe7781a400 
0x00007ffe7781a190:  0x00007ffe7781a2a6  0x0000000000000000 
0x00007ffe7781a1a0:  0x00007ffe7781a2a7  0x0000000000daa030 
0x00007ffe7781a1b0:  0x00007fac782ce008  0x0000000000000110 
0x00007ffe7781a1c0:  0x00000000003d0f00  0x0000000000dd8e64 
0x00007ffe7781a1d0:  0x00007fac782cd990  0x000000000000000d 
0x00007ffe7781a1e0:  0x00000000020930a0  0x0000000000dabc9e 
0x00007ffe7781a1f0: <0x0000000000800300 <html/template.(*escaper).escapeList+0x0000000000000000>  0xcd43ec5cb4283a00 
0x00007ffe7781a200:  0x0000000000000006  0x00000000028b43c0 
0x00007ffe7781a210:  0x00007ffe7781a4c0  0x0000000000000000 
0x00007ffe7781a220:  0x00000000027063a0  0x0000000000d98eb2 
0x00007ffe7781a230:  0x0000000002736c80  0x00000000004013e1 
0x00007ffe7781a240:  0x0000000000000020  0x000000000269d563 
0x00007ffe7781a250:  0x0000000000000828  0x0000000000da38e1 
0x00007ffe7781a260:  0x0000000002701760  0x0000000000000001 
0x00007ffe7781a270:  0x000000000000000a  0x00000000028b43c0 
0x00007ffe7781a280:  0x0000000000000000  0x00000000027063a0 
0x00007ffe7781a290:  0x0000000000000006  0x0000000000da51d9 
0x00007ffe7781a2a0:  0x000000000269d4e0  0x0000000000da5983 
0x00007ffe7781a2b0:  0x000000000269d4e0  0x000000000000000a 
0x00007ffe7781a2c0:  0x00000000028b43c0  0x0000000000da328a 
0x00007ffe7781a2d0:  0x000000000269da68  0xcd43ec5cb4283a00 
0x00007ffe7781a2e0:  0x000000000269da68  0x000000000269da68 
runtime: g 0: unknown pc 0xdabcab
stack: frame={sp:0x7ffe7781a1f0, fp:0x0} stack=[0x7ffe7701b670,0x7ffe7781a680)
0x00007ffe7781a0f0:  0x0000000000069c3f  0x00007ffe7781a118 
0x00007ffe7781a100:  0x0000000000e229f0  0x000000001c000004 
0x00007ffe7781a110:  0x0000000000d98f20  0x0000000000000000 
0x00007ffe7781a120:  0x00007facbee6fc40  0x68007ffe7781a310 
0x00007ffe7781a130:  0x000000c000044000  0x000000c00014e000 
0x00007ffe7781a140:  0x0000000000000000  0x0000000000000000 
0x00007ffe7781a150:  0x0000000000000000  0x0000000000000000 
0x00007ffe7781a160:  0x0000000000000001  0x000000c000044000 
0x00007ffe7781a170:  0x00007ffe7781a358  0x0000000000ddb33d 
0x00007ffe7781a180:  0x00007fac782cd6c0  0x00007ffe7781a400 
0x00007ffe7781a190:  0x00007ffe7781a2a6  0x0000000000000000 
0x00007ffe7781a1a0:  0x00007ffe7781a2a7  0x0000000000daa030 
0x00007ffe7781a1b0:  0x00007fac782ce008  0x0000000000000110 
0x00007ffe7781a1c0:  0x00000000003d0f00  0x0000000000dd8e64 
0x00007ffe7781a1d0:  0x00007fac782cd990  0x000000000000000d 
0x00007ffe7781a1e0:  0x00000000020930a0  0x0000000000dabc9e 
0x00007ffe7781a1f0: <0x0000000000800300 <html/template.(*escaper).escapeList+0x0000000000000000>  0xcd43ec5cb4283a00 
0x00007ffe7781a200:  0x0000000000000006  0x00000000028b43c0 
0x00007ffe7781a210:  0x00007ffe7781a4c0  0x0000000000000000 
0x00007ffe7781a220:  0x00000000027063a0  0x0000000000d98eb2 
0x00007ffe7781a230:  0x0000000002736c80  0x00000000004013e1 
0x00007ffe7781a240:  0x0000000000000020  0x000000000269d563 
0x00007ffe7781a250:  0x0000000000000828  0x0000000000da38e1 
0x00007ffe7781a260:  0x0000000002701760  0x0000000000000001 
0x00007ffe7781a270:  0x000000000000000a  0x00000000028b43c0 
0x00007ffe7781a280:  0x0000000000000000  0x00000000027063a0 
0x00007ffe7781a290:  0x0000000000000006  0x0000000000da51d9 
0x00007ffe7781a2a0:  0x000000000269d4e0  0x0000000000da5983 
0x00007ffe7781a2b0:  0x000000000269d4e0  0x000000000000000a 
0x00007ffe7781a2c0:  0x00000000028b43c0  0x0000000000da328a 
0x00007ffe7781a2d0:  0x000000000269da68  0xcd43ec5cb4283a00 
0x00007ffe7781a2e0:  0x000000000269da68  0x000000000269da68 

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000148740 sp=0xc000148730 pc=0x46b1e8
runtime.main()
        /usr/local/go/src/runtime/proc.go:169 +0x6d fp=0xc0001487e0 sp=0xc000148740 pc=0x43d68d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001487e8 sp=0xc0001487e0 pc=0x46d1c1

rax    0x0
rbx    0x1
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x6
rsp    0x7ffe7781a1f0
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x7ffe7781a4c0
r13    0x0
r14    0x27063a0
r15    0x6
rip    0xdabcab
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**复现步骤**
docker run --name one-api -itd --net host -e SQL_DSN="root:123456@tcp(localhost:3306)/oneapi" -e TZ=Asia/Shanghai -v /workspace/data/one-api:/data justsong/one-api --privilege --security-opt seccomp=unconfined

**预期结果**

**相关截图**
Maybe related to this issue: https://github.com/docker-library/golang/issues/467

<img width="1144" alt="image" src="https://github.com/songquanpeng/one-api/assets/30183023/bf96939c-1d53-48c6-bfcd-4ebe8b5a258a">

**Comment by songkq** [comment]
The above issue has been solved by add `--privileged` 

Another issue:

```
[+] Running 1/0
 ✔ Container one-api  Created                                                                                                                                                                                 0.0s 
Attaching to mysql, one-api, redis
redis    | 1:C 25 Jan 2024 08:23:08.570 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:08.570 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:08.570 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:08.571 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:08.571 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:08.571 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:08.572 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
mysql    | 2024-01-25 16:23:08+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
redis exited with code 1
mysql    | 2024-01-25 16:23:08+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:08+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
one-api  | [SYS] 2024/01/25 - 16:23:09 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:09 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:09 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:09 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp 172.31.0.2:3306: connect: connection refused
one-api  | [FATAL] 2024/01/25 - 16:23:09 | [dial tcp 172.31.0.2:3306: connect: connection refused] 
mysql exited with code 2
one-api exited with code 1
redis exited with code 1
mysql    | 2024-01-25 16:23:09+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
one-api  | [SYS] 2024/01/25 - 16:23:09 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:09 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:09 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:09 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp 172.31.0.2:3306: connect: connection refused
one-api  | [FATAL] 2024/01/25 - 16:23:09 | [dial tcp 172.31.0.2:3306: connect: connection refused] 
mysql    | 2024-01-25 16:23:10+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:10+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
one-api exited with code 1
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
redis exited with code 1
mysql exited with code 2
one-api  | [SYS] 2024/01/25 - 16:23:10 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:10 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:10 | using MySQL as database 
mysql    | 2024-01-25 16:23:10+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
redis    | 1:C 25 Jan 2024 08:23:10.973 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:10.973 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:10.973 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:10.974 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:10.974 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:10.974 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:10.974 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
mysql    | 2024-01-25 16:23:11+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:11+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
mysql    | 2024-01-25 16:23:12+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
redis    | 1:C 25 Jan 2024 08:23:12.227 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:12.227 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:12.227 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:12.228 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:12.228 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:12.228 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:12.228 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
mysql    | 2024-01-25 16:23:12+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:12+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
one-api  | 
one-api  | 2024/01/25 16:23:13 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp 172.31.0.2:3306: connect: no route to host
one-api  | [FATAL] 2024/01/25 - 16:23:13 | [dial tcp 172.31.0.2:3306: connect: no route to host] 
one-api exited with code 1
mysql    | 2024-01-25 16:23:13+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:13+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
redis    | 1:C 25 Jan 2024 08:23:14.320 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:14.320 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:14.320 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:14.321 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:14.321 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:14.321 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:14.321 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
one-api  | [SYS] 2024/01/25 - 16:23:14 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:14 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:14 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:14 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: no such host
one-api  | [FATAL] 2024/01/25 - 16:23:14 | [dial tcp: lookup db on 127.0.0.11:53: no such host] 
one-api exited with code 1
one-api  | [SYS] 2024/01/25 - 16:23:15 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:15 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:15 | using MySQL as database 
mysql    | 2024-01-25 16:23:16+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | 2024-01-25 16:23:16+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:16+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
redis    | 1:C 25 Jan 2024 08:23:17.964 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:17.964 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:17.965 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:17.965 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:17.965 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:17.965 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:17.966 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
one-api  | 
one-api  | 2024/01/25 16:23:18 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp 172.31.0.3:3306: connect: no route to host
one-api  | [FATAL] 2024/01/25 - 16:23:18 | [dial tcp 172.31.0.3:3306: connect: no route to host] 
one-api exited with code 1
mysql    | 2024-01-25 16:23:20+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | 2024-01-25 16:23:20+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:20+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
one-api  | [SYS] 2024/01/25 - 16:23:20 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:20 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:20 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:20 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: no such host
one-api  | [FATAL] 2024/01/25 - 16:23:20 | [dial tcp: lookup db on 127.0.0.11:53: no such host] 
one-api exited with code 1
one-api  | [SYS] 2024/01/25 - 16:23:24 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:24 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:24 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:24 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: no such host
one-api  | [FATAL] 2024/01/25 - 16:23:24 | [dial tcp: lookup db on 127.0.0.11:53: no such host] 
one-api exited with code 1
redis    | 1:C 25 Jan 2024 08:23:24.840 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:24.840 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:24.840 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:24.841 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:24.841 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:24.841 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:24.841 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
mysql    | 2024-01-25 16:23:27+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | 2024-01-25 16:23:27+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql    | 2024-01-25 16:23:27+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
mysql    | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
mysql exited with code 2
one-api  | [SYS] 2024/01/25 - 16:23:31 | SESSION_SECRET is set to an example value, please change it to a random string. 
one-api  | [SYS] 2024/01/25 - 16:23:31 | One API v0.5.12-alpha.1 started 
one-api  | [SYS] 2024/01/25 - 16:23:31 | using MySQL as database 
one-api  | 
one-api  | 2024/01/25 16:23:31 /build/model/main.go:59
one-api  | [error] failed to initialize database, got error dial tcp: lookup db on 127.0.0.11:53: no such host
one-api  | [FATAL] 2024/01/25 - 16:23:31 | [dial tcp: lookup db on 127.0.0.11:53: no such host] 
one-api exited with code 1
redis    | 1:C 25 Jan 2024 08:23:38.076 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 25 Jan 2024 08:23:38.076 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis    | 1:C 25 Jan 2024 08:23:38.076 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis    | 1:M 25 Jan 2024 08:23:38.076 * monotonic clock: POSIX clock_gettime
redis    | 1:M 25 Jan 2024 08:23:38.077 * Running mode=standalone, port=6379.
redis    | 1:M 25 Jan 2024 08:23:38.077 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis    | 1:M 25 Jan 2024 08:23:38.077 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
redis exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
one-api exited with code 0
[+] Stopping 3/0
 ✔ Container one-api  Stopped                                                                                                                                                                                 0.0s 
 ✔ Container mysql    Stopped                                                                                                                                                                                 0.0s 
 ✔ Container redis    Stopped                                                                                                                                                                                 0.0s 
redis exited with code 0
mysql exited with code 0
```
